### ISSUE TITLE
[BUG] Bluedust Blocks cannot be turned back to bluedust

### ISSUE THREAD

**Issue by JoshieGemFinder** [SeriousCreeper/Into-The-Betweenlands-2#1]
**Describe the bug**

Once 9 bluedust have been crafted into a bluedust block, there is no recipe to turn them back into bluedust

**To Reproduce**

1. Craft 9 bluedust into one bluedust block
2. Unable to break down that bluedust block back into 9 bluedust

**Expected behavior**

There would be a crafting recipe (or an anvil hammering/pickaxing recipe) to turn the Bluedust block back into Bluedust

**Screenshots**
![image](https://github.com/SeriousCreeper/Into-The-Betweenlands-2/assets/79513611/e0fe94e0-9f31-4268-a9a6-84b931efca06)

**Version of the pack:**
Into The Betweenlands 2 Alpha 0.6.7

**Comment by SeriousCreeper** [comment]
That was fixed in 0.7.0
